cask_args appdir: '/Applications'

tap 'homebrew/versions'
tap 'caskroom/versions'
tap 'caskroom/fonts'

brew 'coreutils'
brew 'findutils'
brew 'bash'
brew 'bash-completion2'
brew 'wget', args: ['with-iri']
brew 'python'
brew 'python3'
brew 'openssl'
brew 'ffmpeg'
brew 'git'
brew 'git-lfs'
brew 'htop-osx'
brew 'nmap'
brew 'node'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'tree'
brew 'youtube-dl'
brew 'z'
brew 'pass'
brew 'tmux'
brew 'reattach-to-user-namespace', args: ['with-wrap-pbcopy-and-pbpaste']
brew 'argon/mas/mas'
brew 'screenfetch'
brew 'wakeonlan'
brew 'thefuck'
brew 'mongodb'
brew 'speedtest_cli'

cask 'google-chrome-canary'
cask 'iterm2-beta'
cask 'appcleaner'
cask 'spotify'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'wireshark'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'hyperdock'
cask 'java'
cask 'netbeans'
cask 'filezilla'
cask 'firefoxdeveloperedition'
cask 'steam'
cask 'teamviewer'
cask 'atom'
cask 'bartender'
cask 'flux'
cask 'fileshuttle'
cask 'postman'
cask 'kid3'
cask 'teamspeak-client'
cask 'grandperspective'
cask 'libreoffice'

# fonts
cask 'font-source-code-pro'
